### ISSUE TITLE
未定义的中英文项，在代码中直接被写入

### ISSUE THREAD

**Issue by wayofway** [pfzhengd/vue-i18n-aux#2]
希望增加一个新功能：
悬浮自动识别代码中直接写入但未定义的国际化引用，提示补全中英文的json配置文件

**Comment by pfzhengd** [comment]
![image](https://user-images.githubusercontent.com/15017367/59365900-f4d30d00-8d6b-11e9-8a9d-ccc4a93ef30b.png)
https://github.com/pfzhengd/vue-i18n-manage/blob/master/CHANGELOG.zh-CN.md
