### ISSUE TITLE
建议增加输入缓存功能

### ISSUE THREAD

**Issue by wayofway** [pfzhengd/vue-i18n-aux#4]
现在在定义新的国际化配置项时需要制定文件名
例如： index:global.home
建议自动保留上次输入的index:
以增加插件的便利性

**Comment by pfzhengd** [comment]
![image](https://user-images.githubusercontent.com/15017367/59438319-dc272d80-8e25-11e9-8912-fdd27ea9bc65.png)
已添加。

**Comment by pfzhengd** [comment]
https://github.com/pfzhengd/vue-i18n-manage/blob/master/CHANGELOG.zh-CN.md
在v0.5.0中添加。
